---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: apiserver
    app.kubernetes.io/managed-by: brupop
    app.kubernetes.io/part-of: brupop
    brupop.bottlerocket.aws/component: apiserver
  name: brupop-apiserver
  namespace: {{ .Values.namespace }}
spec:
  replicas: 3
  selector:
    matchLabels:
      brupop.bottlerocket.aws/component: apiserver
  strategy:
    rollingUpdate:
      maxUnavailable: 33%
  template:
    metadata:
      labels:
        brupop.bottlerocket.aws/component: apiserver
      namespace: {{ .Values.namespace }}
    spec:
      affinity:
        {{- with .Values.placement.apiserver.podAffinity }}
        podAffinity:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.placement.apiserver.podAntiAffinity }}
        podAntiAffinity:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/os
                    operator: In
                    values:
                      - linux
                  - key: kubernetes.io/arch
                    operator: In
                    values:
                      - amd64
                      - arm64
      {{- with .Values.placement.apiserver.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.placement.apiserver.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.placement.apiserver.priorityClassName }}
      priorityClassName: {{ .Values.placement.apiserver.priorityClassName | quote }}
      {{- end }}
      containers:
        - command:
            - "./apiserver"
          env:
            - name: APISERVER_INTERNAL_PORT
              value: "{{ .Values.apiserver_internal_port }}"
            - name: LOGGING_FORMATTER
              value: "{{ .Values.logging.formatter }}"
            - name: LOGGING_ANSI_ENABLED
              value: "{{ .Values.logging.ansi_enabled }}"
            - name: TRACING_FILTER_DIRECTIVE
              value: "{{ .Values.logging.apiserver.tracing_filter }}"
          image: {{ .Values.image }}
          livenessProbe:
            httpGet:
              path: /ping
              port: {{ .Values.apiserver_internal_port }}
              scheme: HTTPS
            initialDelaySeconds: 5
          name: brupop
          ports:
            - containerPort: {{ .Values.apiserver_internal_port }}
          readinessProbe:
            httpGet:
              path: /ping
              port: {{ .Values.apiserver_internal_port }}
              scheme: HTTPS
            initialDelaySeconds: 5
          resources:
            {{- toYaml .Values.resources.apiserver.resources | nindent 12 }}
          volumeMounts:
            - mountPath: /etc/brupop-tls-keys
              name: bottlerocket-tls-keys
      serviceAccountName: brupop-apiserver-service-account
      volumes:
        - name: bottlerocket-tls-keys
          secret:
            optional: false
            secretName: brupop-apiserver-certificate
