---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: brupop-selfsigned-ca
  namespace: {{ .Values.namespace }}
spec:
  isCA: true
  commonName: brupop-selfsigned-ca
  secretName: brupop-root-ca-secret
  privateKey:
    algorithm: RSA
    encoding: PKCS8
  issuerRef:
    name: selfsigned-issuer
    kind: Issuer
