---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: brupop-controller
    app.kubernetes.io/managed-by: brupop
    app.kubernetes.io/part-of: brupop
    brupop.bottlerocket.aws/component: brupop-controller
  name: brupop-controller-deployment
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      brupop.bottlerocket.aws/component: brupop-controller
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        brupop.bottlerocket.aws/component: brupop-controller
      namespace: {{ .Values.namespace }}
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/os
                    operator: In
                    values:
                      - linux
                  - key: kubernetes.io/arch
                    operator: In
                    values:
                      - amd64
                      - arm64
      containers:
        - command:
            - "./controller"
          env:
            - name: MY_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: MAX_CONCURRENT_UPDATE
              value: "{{ .Values.max_concurrent_updates }}"
            - name: SCHEDULER_CRON_EXPRESSION
              value: "{{ .Values.scheduler_cron_expression}}"
            - name: LOGGING_FORMATTER
              value: "{{ .Values.logging_formatter }}"
            - name: LOGGING_ANSI_ENABLED
              value: "{{ .Values.logging_ansi_enabled }}"
          image: {{ .Values.image }}
          name: brupop
      priorityClassName: brupop-controller-high-priority
      {{ if ((.Values.image_pull_secrets)) }}
      image_pull_secrets: 
        {{ .Values.image_pull_secrets }}
      {{ end }}
      serviceAccountName: brupop-controller-service-account
