---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/component: brupop-controller
    app.kubernetes.io/managed-by: brupop
    app.kubernetes.io/part-of: brupop
    brupop.bottlerocket.aws/component: brupop-controller
  name: brupop-controller-role
  namespace: {{ .Values.namespace }}
rules:
  - apiGroups:
      - brupop.bottlerocket.aws
    resources:
      - bottlerocketshadows
      - bottlerocketshadows/status
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - brupop.bottlerocket.aws
    resources:
      - bottlerocketshadows
    verbs:
      - create
      - patch
      - update
      - delete
  - apiGroups:
      - ""
    resources:
      - nodes
    verbs:
      - get
      - list
      - watch
