version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "daily"
    ignore:
      # tracing-actix-web uses an older version of uuid
      - dependency-name: "uuid"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
