[clarify."sigs.k8s.io/yaml"]
# The package's files are a mix of MIT with contributions attributed to "The Go
# Authors" licensed as BSD-3-Clause.
expression = "MIT AND BSD-3-Clause"
license-files = [
    { path = "LICENSE", hash = 0xcdf3ae00 },
]
