---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: selfsigned-issuer
  namespace: brupop-bottlerocket-aws
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: brupop-selfsigned-ca
  namespace: brupop-bottlerocket-aws
spec:
  isCA: true
  commonName: brupop-selfsigned-ca
  secretName: brupop-root-ca-secret
  privateKey:
    algorithm: RSA
    encoding: PKCS8
  issuerRef:
    name: selfsigned-issuer
    kind: Issuer
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: brupop-root-certificate-issuer
  namespace: brupop-bottlerocket-aws
spec:
  ca:
    secretName: brupop-root-ca-secret
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: brupop-apiserver-certificate
  namespace: brupop-bottlerocket-aws
spec:
  secretName: brupop-apiserver-certificate
  privateKey:
    algorithm: RSA
    encoding: PKCS8
  dnsNames:
    - "*.brupop-bottlerocket-aws.svc.cluster.local"
    - "*.brupop-bottlerocket-aws.svc"
  usages:
    - server auth
    - key encipherment
    - digital signature
  issuerRef:
    name: brupop-root-certificate-issuer
    kind: Issuer
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: brupop-apiserver-client-certificate
  namespace: brupop-bottlerocket-aws
spec:
  secretName: brupop-apiserver-client-certificate
  privateKey:
    algorithm: RSA
    encoding: PKCS8
  dnsNames:
    - "*.brupop-bottlerocket-aws.svc.cluster.local"
    - "*.brupop-bottlerocket-aws.svc"
  usages:
    - client auth
    - key encipherment
    - digital signature
  issuerRef:
    name: brupop-root-certificate-issuer
    kind: Issuer
