name: ci

on:
  push:
    branches:
      - develop
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - name: Setup Go version ${{ matrix.go }}
        uses: actions/setup-go@v1
        with:
          go-version: 1.14.1
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build project
        run: |
          make build test container-test