name: CI

on:

  pull_request:
    paths-ignore:
      - '**.md'
      - 'COPYRIGHT'
      - 'LICENSE**'
      - 'design/**'
    branches: [develop]

  push:
    paths-ignore:
      - '**.md'
      - 'COPYRIGHT'
      - 'LICENSE**'
      - 'design/**'
    branches: [develop]

jobs:

  build-binary:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: rustup update stable
      - run: make build

  build-container:
    name: brupop-image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: make brupop-image
