name: Images
on:
  pull_request:
    paths-ignore:
      - '**.md'
      - 'COPYRIGHT'
      - 'LICENSE**'
      - 'design/**'
jobs:
  build-images:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: make brupop-image
