name: Rust
on:
  pull_request:
    paths-ignore:
      - '**.md'
      - 'COPYRIGHT'
      - 'LICENSE**'
      - 'design/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: rustup update stable
<<<<<<< HEAD
      - run: make build
=======
      - run: make build
>>>>>>> b2a55c5 (Add github build workflows)
