apiVersion: v2
name: bottlerocket-shadow
description: A Helm chart for the Bottlerocket shadow CRD used by the Bottlerocket update operator
home: https://github.com/bottlerocket-os/bottlerocket-update-operator
icon: https://avatars.githubusercontent.com/u/61023959?s=200&v=4
type: application
version: 1.0.0
appVersion: "1.0.0"
sources:
  - https://github.com/bottlerocket-os/bottlerocket-update-operator
